name: tahsinv2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.4.2=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.1=py37he30daa8_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - cryptography=3.0=py37hb09aad4_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.10.2=h5ab3b9f_0
  - idna=2.10=pyh9f0ad1d_0
  - intel-openmp=2020.1=217
  - isort=4.3.21=py37_0
  - jpeg=9b=h024ee3a_2
  - kaggle=1.5.6=py37_1
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_1
  - mccabe=0.6.1=py37_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h516909a_1
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pylint=2.5.3=py37_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python-slugify=4.0.1=pyh9f0ad1d_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - setuptools=49.2.0=py37_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - text-unidecode=1.3=py_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchvision=0.7.0=py37_cu102
  - tqdm=4.48.2=pyh9f0ad1d_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - unidecode=1.1.1=py_0
  - urllib3=1.24.3=py37_0
  - wheel=0.34.2=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/ubuntu/anaconda3/envs/tahsinv2

