name: tahsin
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h8f50634_1000
  - ca-certificates=2020.4.5.2=hecda079_0
  - certifi=2020.4.5.2=py37hc8dfbb8_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37hc8dfbb8_1006
  - cryptography=2.9.2=py37hb09aad4_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cxxfilt=0.2.1=py37h3340039_1
  - freetype=2.9.1=h8a8886c_1
  - idna=2.9=py_1
  - importlib-metadata=1.6.1=py37hc8dfbb8_0
  - importlib_metadata=1.6.1=0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - more-itertools=8.3.0=py_1
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - nvidia-apex=0.1=py37hed6fefa_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_3
  - pluggy=0.13.1=py37hc8dfbb8_1
  - py=1.8.1=py_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytest=5.4.3=py37hc8dfbb8_0
  - python=3.7.7=hcff3b4d_5
  - python_abi=3.7=1_cp37m
  - pytorch=1.5.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.1=py37hac76be4_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=pyh8c360ce_2
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=47.1.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - torchfile=0.1.0=py_0
  - torchvision=0.6.0=py37_cu101
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.1=pyh9f0ad1d_0
  - urllib3=1.25.9=py_0
  - visdom=0.1.8.9=0
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - websocket-client=0.57.0=py37hc8dfbb8_1
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
prefix: /home/ubuntu/anaconda3/envs/tahsin

